FROM node:latest AS build
RUN useradd -m -d /home/fuser -s /bin/bash fuser
WORKDIR /home/fuser
COPY --chown=fuser:fuser package*.json ./
USER fuser
RUN npm install
COPY --chown=fuser:fuser . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80