apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=sujith1319/myapp-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9]+$
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:values.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/msujith1319/myapp.git
    targetRevision: main
    path: deployment/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
