apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: prod
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backend-secret
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: backend
        property: MONGODB_URI