apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dockerhub-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://registry-1.docker.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "email": "{{ .email }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: argocd/dockerhub
        property: username
    - secretKey: token
      remoteRef:
        key: argocd/dockerhub
        property: token
    - secretKey: email
      remoteRef:
        key: argocd/dockerhub
        property: email
