apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-creds
  data:
    - secretKey: username
      remoteRef:
        key: argocd/github
        property: username
    - secretKey: password
      remoteRef:
        key: argocd/github
        property: token

